- name: Setup MongoDB server
  hosts: mongodb_servers
  become: yes
  tasks:
    - name: Install MongoDB client
      apt:
        name: mongodb-clients
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure MongoDB is running
      service:
        name: mongod
        state: started
      when: ansible_os_family == "Debian"
